-- Canonical forecast-store DDL (convention 0.4.0).
-- Generated by: forecast-store ddl --timescale
-- Regenerate rather than hand-editing; the generator is the source of truth.

CREATE SCHEMA IF NOT EXISTS forecast;

CREATE TABLE IF NOT EXISTS forecast.series (
    series_id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name            text COLLATE "C" UNIQUE NOT NULL,
    sample_interval interval NOT NULL,
    timezone        text,
    unit            text,
    description     text,
    metadata        jsonb,
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS forecast.store_tables (
    table_name         text PRIMARY KEY,
    convention_version text NOT NULL,
    config             jsonb NOT NULL,
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION forecast.get_series_id(p_name text)
RETURNS bigint
LANGUAGE plpgsql STABLE AS $$
DECLARE
    v_id bigint;
BEGIN
    SELECT series_id INTO v_id FROM forecast.series WHERE name = p_name;
    IF v_id IS NULL THEN
        RAISE EXCEPTION 'unknown series name: %', p_name
            USING HINT = 'register it first with forecast.register_series(...)';
    END IF;
    RETURN v_id;
END
$$;

CREATE OR REPLACE FUNCTION forecast.register_series(
    p_name            text,
    p_sample_interval interval,
    p_timezone        text DEFAULT NULL,
    p_unit            text DEFAULT NULL,
    p_description     text DEFAULT NULL,
    p_metadata        jsonb DEFAULT NULL)
RETURNS bigint
LANGUAGE plpgsql AS $$
DECLARE
    v_id bigint;
BEGIN
    INSERT INTO forecast.series (name, sample_interval, timezone, unit, description, metadata)
    VALUES (p_name, p_sample_interval, p_timezone, p_unit, p_description, p_metadata)
    ON CONFLICT (name) DO NOTHING
    RETURNING series_id INTO v_id;
    IF v_id IS NULL THEN
        SELECT series_id INTO v_id FROM forecast.series WHERE name = p_name;
    END IF;
    RETURN v_id;
END
$$;

CREATE TABLE IF NOT EXISTS forecast.runs (
    run_id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_name      text,
    model         text NOT NULL,
    model_version text,
    available_at  timestamptz NOT NULL DEFAULT now(),
    recorded_at   timestamptz NOT NULL DEFAULT now(),
    context_start timestamptz,
    context_end   timestamptz,
    params        jsonb
);

CREATE TABLE IF NOT EXISTS forecast.forecasts (
    run_id       uuid NOT NULL,           -- no FK by default; see spec §8
    series_id    bigint NOT NULL,
    target_time  timestamptz NOT NULL,
    available_at timestamptz NOT NULL,    -- denormalized from the run (writable claim)
    recorded_at  timestamptz NOT NULL DEFAULT now(),  -- system clock (never written)
    mean          double precision,
    q05           double precision,
    q10           double precision,
    q30           double precision,
    q50           double precision,
    q70           double precision,
    q90           double precision,
    q95           double precision,
    PRIMARY KEY (series_id, target_time, run_id)
);

CREATE INDEX IF NOT EXISTS forecasts_asof_idx
    ON forecast.forecasts (series_id, target_time, available_at DESC);

CREATE OR REPLACE VIEW forecast.latest_forecasts AS
SELECT DISTINCT ON (f.series_id, f.target_time)
       s.name AS series_name,
       f.series_id, f.target_time, f.available_at, f.run_id,
       f.mean, f.q05, f.q10, f.q30, f.q50, f.q70, f.q90, f.q95
FROM forecast.forecasts f
JOIN forecast.series s USING (series_id)
ORDER BY f.series_id, f.target_time, f.available_at DESC;

CREATE TABLE IF NOT EXISTS forecast.predictors (
    series_id    bigint NOT NULL,
    target_time  timestamptz NOT NULL,
    available_at timestamptz NOT NULL,    -- vendor publication time: stated, never defaulted
    recorded_at  timestamptz NOT NULL DEFAULT now(),  -- when the store ingested it
    value         double precision,
    PRIMARY KEY (series_id, target_time, available_at)
);

CREATE TABLE IF NOT EXISTS forecast.actuals (
    series_id    bigint NOT NULL,
    target_time  timestamptz NOT NULL,
    available_at timestamptz NOT NULL DEFAULT now(),
    recorded_at  timestamptz NOT NULL DEFAULT now(),
    value        double precision,
    PRIMARY KEY (series_id, target_time, available_at)
);

CREATE TABLE IF NOT EXISTS forecast.evaluation_runs (
    eval_run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_name    text NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    params      jsonb
);

CREATE TABLE IF NOT EXISTS forecast.evaluation_series (
    eval_series_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    run_name  text NOT NULL,
    series_id bigint NOT NULL,
    filtering text NOT NULL,
    win       text NOT NULL,
    quantile  text NOT NULL DEFAULT 'global',
    metric    text NOT NULL,
    UNIQUE (run_name, series_id, filtering, win, quantile, metric)
);

CREATE TABLE IF NOT EXISTS forecast.evaluation_metrics (
    eval_series_id bigint NOT NULL,
    ts             timestamptz NOT NULL,
    eval_run_id    uuid NOT NULL,
    value          double precision,
    PRIMARY KEY (eval_series_id, ts, eval_run_id)
);

CREATE OR REPLACE FUNCTION forecast.belief_guard() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
    IF NEW.value IS NOT DISTINCT FROM OLD.value THEN
        RETURN NULL;  -- identical re-delivery: idempotent skip
    END IF;
    RAISE EXCEPTION 'conflicting belief for series % at %: stored %, incoming % (single-belief table, spec 6.1)',
        OLD.series_id, OLD.target_time, OLD.value, NEW.value
        USING ERRCODE = 'integrity_constraint_violation';
END $fn$;

INSERT INTO forecast.store_tables (table_name, convention_version, config)
VALUES
    ('forecasts', '0.4.0', '{"enforcement": "monitor", "has_mean": true, "has_runs": true, "knowledge_column": "available_at", "quantile_band": ["0.05", "0.1", "0.3", "0.5", "0.7", "0.9", "0.95"], "role": "own_forecasts", "value_columns": ["mean", "q05", "q10", "q30", "q50", "q70", "q90", "q95"]}'::jsonb),
    ('predictors', '0.4.0', '{"enforcement": "monitor", "has_runs": false, "has_value": true, "knowledge_column": "available_at", "quantile_band": [], "role": "predictors", "value_columns": ["value"]}'::jsonb),
    ('actuals', '0.4.0', '{"enforcement": "monitor", "has_runs": false, "knowledge_column": "available_at", "revisions": true, "role": "actuals", "value_columns": ["value"]}'::jsonb),
    ('evaluation_runs', '0.4.0', '{"role": "evaluation"}'::jsonb),
    ('evaluation_series', '0.4.0', '{"role": "evaluation"}'::jsonb),
    ('evaluation_metrics', '0.4.0', '{"role": "evaluation"}'::jsonb)
ON CONFLICT (table_name) DO NOTHING;

SELECT create_hypertable('forecast.forecasts', 'target_time', if_not_exists => TRUE, migrate_data => TRUE);

ALTER TABLE forecast.forecasts SET (timescaledb.enable_columnstore, timescaledb.segmentby = 'series_id', timescaledb.orderby = 'target_time DESC, available_at DESC');

CALL add_columnstore_policy('forecast.forecasts', after => INTERVAL '7 days', if_not_exists => true);

SELECT create_hypertable('forecast.predictors', 'target_time', if_not_exists => TRUE, migrate_data => TRUE);

ALTER TABLE forecast.predictors SET (timescaledb.enable_columnstore, timescaledb.segmentby = 'series_id', timescaledb.orderby = 'target_time DESC, available_at DESC');

CALL add_columnstore_policy('forecast.predictors', after => INTERVAL '7 days', if_not_exists => true);

SELECT create_hypertable('forecast.actuals', 'target_time', if_not_exists => TRUE, migrate_data => TRUE);

ALTER TABLE forecast.actuals SET (timescaledb.enable_columnstore, timescaledb.segmentby = 'series_id', timescaledb.orderby = 'target_time DESC, available_at DESC');

CALL add_columnstore_policy('forecast.actuals', after => INTERVAL '7 days', if_not_exists => true);

CREATE OR REPLACE FUNCTION forecast.data_quality_sweep(scan_window interval DEFAULT '2 days')
RETURNS TABLE(issue text, table_name text, series_id bigint, n bigint)
LANGUAGE sql STABLE AS $$
    SELECT 'orphan_series'::text, 'forecasts'::text, p.series_id, count(*)
    FROM forecast.forecasts p LEFT JOIN forecast.series sr USING (series_id)
    WHERE p.recorded_at > now() - scan_window AND sr.series_id IS NULL
    GROUP BY p.series_id
    UNION ALL
    SELECT 'off_grid_target_time', 'forecasts', p.series_id, count(*)
    FROM forecast.forecasts p JOIN forecast.series sr USING (series_id)
    WHERE p.recorded_at > now() - scan_window
      AND sr.sample_interval > interval '0'
      AND sr.sample_interval < interval '28 days'
      AND time_bucket(sr.sample_interval, p.target_time) <> p.target_time
    GROUP BY p.series_id
    UNION ALL
    SELECT 'orphan_series'::text, 'predictors'::text, p.series_id, count(*)
    FROM forecast.predictors p LEFT JOIN forecast.series sr USING (series_id)
    WHERE p.recorded_at > now() - scan_window AND sr.series_id IS NULL
    GROUP BY p.series_id
    UNION ALL
    SELECT 'off_grid_target_time', 'predictors', p.series_id, count(*)
    FROM forecast.predictors p JOIN forecast.series sr USING (series_id)
    WHERE p.recorded_at > now() - scan_window
      AND sr.sample_interval > interval '0'
      AND sr.sample_interval < interval '28 days'
      AND time_bucket(sr.sample_interval, p.target_time) <> p.target_time
    GROUP BY p.series_id
    UNION ALL
    SELECT 'orphan_series'::text, 'actuals'::text, p.series_id, count(*)
    FROM forecast.actuals p LEFT JOIN forecast.series sr USING (series_id)
    WHERE p.recorded_at > now() - scan_window AND sr.series_id IS NULL
    GROUP BY p.series_id
    UNION ALL
    SELECT 'off_grid_target_time', 'actuals', p.series_id, count(*)
    FROM forecast.actuals p JOIN forecast.series sr USING (series_id)
    WHERE p.recorded_at > now() - scan_window
      AND sr.sample_interval > interval '0'
      AND sr.sample_interval < interval '28 days'
      AND time_bucket(sr.sample_interval, p.target_time) <> p.target_time
    GROUP BY p.series_id
$$;
