-- Generated by: forecast-store ddl --section catalog --timescale
-- (package: pip install forecast-store) -- do not hand-edit; regenerate.
--
-- The decision-invariant layer: paste once per store, before any points
-- table. Registry + resolvers, the store_tables self-description catalog,
-- run provenance, evaluation tables, guard functions, and the
-- catalog-driven data_quality_sweep (it discovers points tables from their
-- store_tables declarations, so it never needs regeneration).

CREATE SCHEMA IF NOT EXISTS forecast;

CREATE TABLE IF NOT EXISTS forecast.series (
    series_id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name            text COLLATE "C" UNIQUE NOT NULL,
    sample_interval interval NOT NULL,
    timezone        text,
    unit            text,
    description     text,
    metadata        jsonb,
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS forecast.store_tables (
    table_name         text PRIMARY KEY,
    convention_version text NOT NULL,
    config             jsonb NOT NULL,
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION forecast.get_series_id(p_name text)
RETURNS bigint
LANGUAGE plpgsql STABLE AS $$
DECLARE
    v_id bigint;
BEGIN
    SELECT series_id INTO v_id FROM forecast.series WHERE name = p_name;
    IF v_id IS NULL THEN
        RAISE EXCEPTION 'unknown series name: %', p_name
            USING HINT = 'register it first with forecast.register_series(...)';
    END IF;
    RETURN v_id;
END
$$;

CREATE OR REPLACE FUNCTION forecast.register_series(
    p_name            text,
    p_sample_interval interval,
    p_timezone        text DEFAULT NULL,
    p_unit            text DEFAULT NULL,
    p_description     text DEFAULT NULL,
    p_metadata        jsonb DEFAULT NULL)
RETURNS bigint
LANGUAGE plpgsql AS $$
DECLARE
    v_id bigint;
BEGIN
    INSERT INTO forecast.series (name, sample_interval, timezone, unit, description, metadata)
    VALUES (p_name, p_sample_interval, p_timezone, p_unit, p_description, p_metadata)
    ON CONFLICT (name) DO NOTHING
    RETURNING series_id INTO v_id;
    IF v_id IS NULL THEN
        SELECT series_id INTO v_id FROM forecast.series WHERE name = p_name;
    END IF;
    RETURN v_id;
END
$$;

CREATE TABLE IF NOT EXISTS forecast.runs (
    run_id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_name      text,
    model         text NOT NULL,
    model_version text,
    available_at  timestamptz NOT NULL DEFAULT now(),
    recorded_at   timestamptz NOT NULL DEFAULT now(),
    context_start timestamptz,
    context_end   timestamptz,
    params        jsonb
);

CREATE TABLE IF NOT EXISTS forecast.evaluation_runs (
    eval_run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_name    text NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    params      jsonb
);

CREATE TABLE IF NOT EXISTS forecast.evaluation_series (
    eval_series_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    run_name  text NOT NULL,
    series_id bigint NOT NULL,
    filtering text NOT NULL,
    win       text NOT NULL,
    quantile  text NOT NULL DEFAULT 'global',
    metric    text NOT NULL,
    UNIQUE (run_name, series_id, filtering, win, quantile, metric)
);

CREATE TABLE IF NOT EXISTS forecast.evaluation_metrics (
    eval_series_id bigint NOT NULL,
    ts             timestamptz NOT NULL,
    eval_run_id    uuid NOT NULL,
    value          double precision,
    PRIMARY KEY (eval_series_id, ts, eval_run_id)
);

CREATE OR REPLACE FUNCTION forecast.belief_guard() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
    IF NEW.value IS NOT DISTINCT FROM OLD.value THEN
        RETURN NULL;  -- identical re-delivery: idempotent skip
    END IF;
    RAISE EXCEPTION 'conflicting belief for series % at %: stored %, incoming % (single-belief table, spec 6.1)',
        OLD.series_id, OLD.target_time, OLD.value, NEW.value
        USING ERRCODE = 'integrity_constraint_violation';
END $fn$;

INSERT INTO forecast.store_tables (table_name, convention_version, config)
VALUES
    ('evaluation_runs', '0.4.0', '{"role": "evaluation"}'::jsonb),
    ('evaluation_series', '0.4.0', '{"role": "evaluation"}'::jsonb),
    ('evaluation_metrics', '0.4.0', '{"role": "evaluation"}'::jsonb)
ON CONFLICT (table_name) DO NOTHING;

CREATE OR REPLACE FUNCTION forecast.data_quality_sweep(scan_window interval DEFAULT '2 days')
RETURNS TABLE(issue text, table_name text, series_id bigint, n bigint)
LANGUAGE plpgsql STABLE AS $fn$
DECLARE
    t record;
BEGIN
    FOR t IN
        SELECT st.table_name AS name,
               coalesce((st.config->>'has_target_time_observed')::boolean, false)
                   AS observed
        FROM forecast.store_tables st
        WHERE st.config->>'role' IN ('actuals', 'predictors', 'forecasts')
          AND to_regclass(format('forecast.%I', st.table_name)) IS NOT NULL
        ORDER BY st.table_name
    LOOP
        RETURN QUERY EXECUTE format($q$
            SELECT 'orphan_series'::text, %L::text, p.series_id, count(*)
            FROM forecast.%I p LEFT JOIN forecast.series sr USING (series_id)
            WHERE p.recorded_at > now() - $1 AND sr.series_id IS NULL
            GROUP BY p.series_id$q$, t.name, t.name) USING scan_window;
        RETURN QUERY EXECUTE format($q$
            SELECT 'off_grid_target_time'::text, %L::text, p.series_id, count(*)
            FROM forecast.%I p JOIN forecast.series sr USING (series_id)
            WHERE p.recorded_at > now() - $1
              AND sr.sample_interval > interval '0'
              AND sr.sample_interval < interval '28 days'
              AND time_bucket(sr.sample_interval, p.target_time) <> p.target_time
            GROUP BY p.series_id$q$, t.name, t.name) USING scan_window;
        IF t.observed THEN
            RETURN QUERY EXECUTE format($q$
                SELECT 'observed_outside_bucket'::text, %L::text, p.series_id, count(*)
                FROM forecast.%I p JOIN forecast.series sr USING (series_id)
                WHERE p.recorded_at > now() - $1
                  AND p.target_time_observed IS NOT NULL
                  AND (p.target_time_observed < p.target_time
                       OR p.target_time_observed >= p.target_time + sr.sample_interval)
                GROUP BY p.series_id$q$, t.name, t.name) USING scan_window;
        END IF;
    END LOOP;
END
$fn$;
