-- Generated from the forecast-store package (pip install forecast-store);
-- do not hand-edit; regenerate. Each block below is self-contained: the
-- table, its index/view/triggers, its store_tables declaration row, and its
-- TimescaleDB layer. Paste catalog-ddl.sql first, then one block per stream
-- you classified. The catalog-driven sweep picks each block up from its
-- declaration row automatically.

-- ============================================================
-- Default store: forecasts (7-level band + mean), predictors,
-- revisioned actuals.
-- Generated by: forecast-store ddl --section tables --timescale
-- ============================================================

CREATE TABLE IF NOT EXISTS forecast.forecasts (
    run_id       uuid NOT NULL,           -- no FK by default; see spec §8
    series_id    bigint NOT NULL,
    target_time  timestamptz NOT NULL,
    available_at timestamptz NOT NULL,    -- denormalized from the run (writable claim)
    recorded_at  timestamptz NOT NULL DEFAULT now(),  -- system clock (never written)
    mean          double precision,
    q05           double precision,
    q10           double precision,
    q30           double precision,
    q50           double precision,
    q70           double precision,
    q90           double precision,
    q95           double precision,
    PRIMARY KEY (series_id, target_time, run_id)
);

CREATE INDEX IF NOT EXISTS forecasts_asof_idx
    ON forecast.forecasts (series_id, target_time, available_at DESC);

CREATE OR REPLACE VIEW forecast.latest_forecasts AS
SELECT DISTINCT ON (f.series_id, f.target_time)
       s.name AS series_name,
       f.series_id, f.target_time, f.available_at, f.run_id,
       f.mean, f.q05, f.q10, f.q30, f.q50, f.q70, f.q90, f.q95
FROM forecast.forecasts f
JOIN forecast.series s USING (series_id)
ORDER BY f.series_id, f.target_time, f.available_at DESC;

INSERT INTO forecast.store_tables (table_name, convention_version, config)
VALUES
    ('forecasts', '0.4.0', '{"enforcement": "monitor", "has_mean": true, "has_runs": true, "knowledge_column": "available_at", "quantile_band": ["0.05", "0.1", "0.3", "0.5", "0.7", "0.9", "0.95"], "role": "own_forecasts", "value_columns": ["mean", "q05", "q10", "q30", "q50", "q70", "q90", "q95"]}'::jsonb)
ON CONFLICT (table_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS forecast.predictors (
    series_id    bigint NOT NULL,
    target_time  timestamptz NOT NULL,
    available_at timestamptz NOT NULL,    -- vendor publication time: stated, never defaulted
    recorded_at  timestamptz NOT NULL DEFAULT now(),  -- when the store ingested it
    value         double precision,
    PRIMARY KEY (series_id, target_time, available_at)
);

INSERT INTO forecast.store_tables (table_name, convention_version, config)
VALUES
    ('predictors', '0.4.0', '{"enforcement": "monitor", "has_runs": false, "has_value": true, "knowledge_column": "available_at", "quantile_band": [], "role": "predictors", "value_columns": ["value"]}'::jsonb)
ON CONFLICT (table_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS forecast.actuals (
    series_id    bigint NOT NULL,
    target_time  timestamptz NOT NULL,
    available_at timestamptz NOT NULL DEFAULT now(),
    recorded_at  timestamptz NOT NULL DEFAULT now(),
    value        double precision,
    PRIMARY KEY (series_id, target_time, available_at)
);

INSERT INTO forecast.store_tables (table_name, convention_version, config)
VALUES
    ('actuals', '0.4.0', '{"enforcement": "monitor", "has_runs": false, "knowledge_column": "available_at", "revisions": true, "role": "actuals", "value_columns": ["value"]}'::jsonb)
ON CONFLICT (table_name) DO NOTHING;

SELECT create_hypertable('forecast.forecasts', 'target_time', if_not_exists => TRUE, migrate_data => TRUE);

ALTER TABLE forecast.forecasts SET (timescaledb.enable_columnstore, timescaledb.segmentby = 'series_id', timescaledb.orderby = 'target_time DESC, available_at DESC');

CALL add_columnstore_policy('forecast.forecasts', after => INTERVAL '7 days', if_not_exists => true);

SELECT create_hypertable('forecast.predictors', 'target_time', if_not_exists => TRUE, migrate_data => TRUE);

ALTER TABLE forecast.predictors SET (timescaledb.enable_columnstore, timescaledb.segmentby = 'series_id', timescaledb.orderby = 'target_time DESC, available_at DESC');

CALL add_columnstore_policy('forecast.predictors', after => INTERVAL '7 days', if_not_exists => true);

SELECT create_hypertable('forecast.actuals', 'target_time', if_not_exists => TRUE, migrate_data => TRUE);

ALTER TABLE forecast.actuals SET (timescaledb.enable_columnstore, timescaledb.segmentby = 'series_id', timescaledb.orderby = 'target_time DESC, available_at DESC');

CALL add_columnstore_policy('forecast.actuals', after => INTERVAL '7 days', if_not_exists => true);


-- ============================================================
-- VARIANT: single-belief actuals (spec 6.1) -- only for pipelines you own,
-- where a second belief is a defect. PK admits one belief per target; the
-- belief_guard trigger (function ships in the catalog) makes the upsert
-- write skip-or-raise. Use IN PLACE OF the actuals block above.
-- Generated by: forecast-store ddl --section tables --single-belief-actuals --timescale
-- ============================================================

CREATE TABLE IF NOT EXISTS forecast.actuals (
    series_id    bigint NOT NULL,
    target_time  timestamptz NOT NULL,
    available_at timestamptz NOT NULL DEFAULT now(),
    recorded_at  timestamptz NOT NULL DEFAULT now(),
    value        double precision,
    PRIMARY KEY (series_id, target_time)
);

CREATE OR REPLACE TRIGGER belief_guard BEFORE UPDATE ON forecast.actuals
FOR EACH ROW EXECUTE FUNCTION forecast.belief_guard();

INSERT INTO forecast.store_tables (table_name, convention_version, config)
VALUES
    ('actuals', '0.4.0', '{"enforcement": "monitor", "has_runs": false, "knowledge_column": "available_at", "revisions": false, "role": "actuals", "value_columns": ["value"]}'::jsonb)
ON CONFLICT (table_name) DO NOTHING;

SELECT create_hypertable('forecast.actuals', 'target_time', if_not_exists => TRUE, migrate_data => TRUE);

ALTER TABLE forecast.actuals SET (timescaledb.enable_columnstore, timescaledb.segmentby = 'series_id', timescaledb.orderby = 'target_time DESC, available_at DESC');

CALL add_columnstore_policy('forecast.actuals', after => INTERVAL '7 days', if_not_exists => true);

-- ============================================================
-- VARIANT: an additional forecast-log instance with its own band (spec 7.2)
-- -- e.g. a decile-only model. Name and band are yours; columns derive from
-- the band by the bijection (q10 <-> 0.1). Add ALONGSIDE the blocks above.
-- Generated by: python -c "...ForecastLogSpec('forecasts_deciles',
--   quantile_band=('0.1','0.3','0.5','0.7','0.9'), has_mean=False)..."
-- ============================================================

CREATE TABLE IF NOT EXISTS forecast.forecasts_deciles (
    run_id       uuid NOT NULL,           -- no FK by default; see spec §8
    series_id    bigint NOT NULL,
    target_time  timestamptz NOT NULL,
    available_at timestamptz NOT NULL,    -- denormalized from the run (writable claim)
    recorded_at  timestamptz NOT NULL DEFAULT now(),  -- system clock (never written)
    q10           double precision,
    q30           double precision,
    q50           double precision,
    q70           double precision,
    q90           double precision,
    PRIMARY KEY (series_id, target_time, run_id)
);

CREATE INDEX IF NOT EXISTS forecasts_deciles_asof_idx
    ON forecast.forecasts_deciles (series_id, target_time, available_at DESC);

CREATE OR REPLACE VIEW forecast.latest_forecasts_deciles AS
SELECT DISTINCT ON (f.series_id, f.target_time)
       s.name AS series_name,
       f.series_id, f.target_time, f.available_at, f.run_id,
       f.q10, f.q30, f.q50, f.q70, f.q90
FROM forecast.forecasts_deciles f
JOIN forecast.series s USING (series_id)
ORDER BY f.series_id, f.target_time, f.available_at DESC;

INSERT INTO forecast.store_tables (table_name, convention_version, config)
VALUES
    ('forecasts_deciles', '0.4.0', '{"enforcement": "monitor", "has_mean": false, "has_runs": true, "knowledge_column": "available_at", "quantile_band": ["0.1", "0.3", "0.5", "0.7", "0.9"], "role": "own_forecasts", "value_columns": ["q10", "q30", "q50", "q70", "q90"]}'::jsonb)
ON CONFLICT (table_name) DO NOTHING;

SELECT create_hypertable('forecast.forecasts_deciles', 'target_time', if_not_exists => TRUE, migrate_data => TRUE);

ALTER TABLE forecast.forecasts_deciles SET (timescaledb.enable_columnstore, timescaledb.segmentby = 'series_id', timescaledb.orderby = 'target_time DESC, available_at DESC');

CALL add_columnstore_policy('forecast.forecasts_deciles', after => INTERVAL '7 days', if_not_exists => true);
